// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baihpabnxkijbltikygg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaWhwYWJueGtpamJsdGlreWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU0OTEsImV4cCI6MjA2NTU4MTQ5MX0.sdeKj37SX9FVWJrQNAT4YO7WihKEUcSUIfCm2y_ABpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
